// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7mW2eSHHwj-bQsxwsRlVGzcGdZFkuRg4',
    appId: '1:448831081151:web:b81b44a3175ec587cd540a',
    messagingSenderId: '448831081151',
    projectId: 'flutter-authen-ef86d',
    authDomain: 'flutter-authen-ef86d.firebaseapp.com',
    storageBucket: 'flutter-authen-ef86d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLz7XIADJIgTXjUDG6ohqCFh_njL1499U',
    appId: '1:448831081151:android:4b1ad8447a4a5a12cd540a',
    messagingSenderId: '448831081151',
    projectId: 'flutter-authen-ef86d',
    storageBucket: 'flutter-authen-ef86d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDaW0Ku9ztOFedMT8HbEEbLc5FuqAKJwc',
    appId: '1:448831081151:ios:606b1b04ccca9b13cd540a',
    messagingSenderId: '448831081151',
    projectId: 'flutter-authen-ef86d',
    storageBucket: 'flutter-authen-ef86d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDaW0Ku9ztOFedMT8HbEEbLc5FuqAKJwc',
    appId: '1:448831081151:ios:606b1b04ccca9b13cd540a',
    messagingSenderId: '448831081151',
    projectId: 'flutter-authen-ef86d',
    storageBucket: 'flutter-authen-ef86d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7mW2eSHHwj-bQsxwsRlVGzcGdZFkuRg4',
    appId: '1:448831081151:web:95cad528c4ee8545cd540a',
    messagingSenderId: '448831081151',
    projectId: 'flutter-authen-ef86d',
    authDomain: 'flutter-authen-ef86d.firebaseapp.com',
    storageBucket: 'flutter-authen-ef86d.firebasestorage.app',
  );
}
